#---------------Discord------------------#
162.159.138.232 discord.com
162.159.137.232 discord.com
162.159.128.233 discord.com
162.159.135.232 discord.com
162.159.138.232 updates.discord.com
162.159.137.232 updates.discord.com
162.159.128.233 updates.discord.com
162.159.135.232 updates.discord.com
#----------------Github------------------#
146.75.22.132 objects.githubusercontent.com
146.75.22.132 raw.githubusercontent.com
146.75.22.132 release-assets.githubusercontent.com
146.75.22.132 private-user-images.githubusercontent.com
146.75.22.132 gist.githubusercontent.com
146.75.22.132 avatars.githubusercontent.com
146.75.22.132 media.githubusercontent.com
146.75.22.132 avatars0.githubusercontent.com
146.75.22.132 avatars1.githubusercontent.com
146.75.22.132 avatars2.githubusercontent.com
146.75.22.132 avatars3.githubusercontent.com
146.75.22.132 avatars4.githubusercontent.com
146.75.22.132 avatars5.githubusercontent.com
146.75.22.132 avatars6.githubusercontent.com
146.75.22.132 avatars7.githubusercontent.com
146.75.22.132 avatars8.githubusercontent.com
146.75.22.132 camo.githubusercontent.com
146.75.22.132 cloud.githubusercontent.com
#--------------DNS(IPv4)----------------#
1.1.1.1 one.one.one.one
8.8.4.4 dns.google
9.9.9.9 dns.quad9.net
76.76.2.11 freedns.controld.com
146.112.41.2 doh.opendns.com
104.16.249.249 cloudflare-dns.com
185.71.138.138 wikimedia-dns.org
185.228.168.168 doh.cleanbrowsing.org
194.169.169.169 dns.surfsharkdns.com
223.5.5.5 dns.alidns.com
#--------------DNS(IPv6)----------------#
2606:4700:4700::1111 one.one.one.one
2001:4860:4860::8844 dns.google
2620:fe::fe dns.quad9.net
2606:1a40::11 freedns.controld.com
2620:119:fc::2 doh.opendns.com
2606:4700::6810:f9f9 cloudflare-dns.com
2001:67c:930::1 wikimedia-dns.org
2a09:a707:169:: dns.surfsharkdns.com
2400:3200:baba::1 dns.alidns.com
#---------------------------------------#