#---------------Discord------------------#
162.159.138.232 discord.com
162.159.137.232 discord.com
162.159.128.233 discord.com
162.159.135.232 discord.com
162.159.138.232 updates.discord.com
162.159.137.232 updates.discord.com
162.159.128.233 updates.discord.com
162.159.135.232 updates.discord.com
#----------------Github------------------#
146.75.22.132 objects.githubusercontent.com
146.75.22.132 raw.githubusercontent.com
146.75.22.132 release-assets.githubusercontent.com
146.75.22.132 private-user-images.githubusercontent.com
146.75.22.132 gist.githubusercontent.com
146.75.22.132 avatars.githubusercontent.com
146.75.22.132 media.githubusercontent.com
146.75.22.132 avatars0.githubusercontent.com
146.75.22.132 avatars1.githubusercontent.com
146.75.22.132 avatars2.githubusercontent.com
146.75.22.132 avatars3.githubusercontent.com
146.75.22.132 avatars4.githubusercontent.com
146.75.22.132 avatars5.githubusercontent.com
146.75.22.132 avatars6.githubusercontent.com
146.75.22.132 avatars7.githubusercontent.com
146.75.22.132 avatars8.githubusercontent.com
146.75.22.132 camo.githubusercontent.com
146.75.22.132 cloud.githubusercontent.com
#---------------------------------------#